# Generated by Django 4.2.4 on 2023-08-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("selling_price", models.FloatField()),
                ("discounted_price", models.FloatField()),
                ("description", models.TextField()),
                ("prodapp", models.TextField(default="1")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FM", "Fresh Meat"),
                            ("FM", "Fresh Milk"),
                            ("FD", "Fruit Drinks"),
                            ("FR", "Fresh Fruits"),
                            ("BS", "Biscuits Snack"),
                            ("SF", "Sea Foods"),
                            ("FB", "Fresh Bakery"),
                            ("VG", "Vegetables"),
                        ],
                        max_length=25,
                    ),
                ),
                ("product_image", models.ImageField(upload_to="product")),
            ],
        ),
    ]
