# Generated by Django 4.2.4 on 2023-08-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="composition",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("FM", "Fresh Meat"),
                    ("FR", "Fresh Fruits"),
                    ("FM2", "Fresh Milk"),
                    ("BS", "Biscuits Snack"),
                    ("VG", "Vegetables"),
                    ("SF", "Sea Foods"),
                    ("FD", "Fruit Drinks"),
                    ("FB", "Fresh Bakery"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="product", name="prodapp", field=models.TextField(default=""),
        ),
    ]
