# Generated by Django 4.2.4 on 2023-08-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_product_composition_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("FM", "Fresh Meat"),
                    ("FR", "Fresh Fruits"),
                    ("FB", "Fresh Bakery"),
                    ("VG", "Vegetables"),
                    ("BS", "Biscuits Snack"),
                    ("FM2", "Fresh Milk"),
                    ("FD", "Fruit Drinks"),
                    ("SF", "Sea Foods"),
                ],
                max_length=25,
            ),
        ),
    ]
