# Generated by Django 4.2.4 on 2023-08-18 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0003_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("SF", "Sea Foods"),
                    ("BS", "Biscuits Snack"),
                    ("FD", "Fruit Drinks"),
                    ("FR", "Fresh Fruits"),
                    ("VG", "Vegetables"),
                    ("FM", "Fresh Meat"),
                    ("FM2", "Fresh Milk"),
                    ("FB", "Fresh Bakery"),
                ],
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("locality", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=50)),
                ("mobile", models.IntegerField(default=0)),
                ("zipcode", models.IntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("KA", "Karnataka"),
                            ("TR", "Tripura"),
                            ("AR", "Arunachal Pradesh"),
                            ("PY", "Pondicherry"),
                            ("CH", "Chandigarh"),
                            ("TN", "Tamil Nadu"),
                            ("TS", "Telangana"),
                            ("MP", "Madhya Pradesh"),
                            ("DL", "Delhi"),
                            ("ML", "Meghalaya"),
                            ("LA", "Ladakh"),
                            ("HR", "Haryana"),
                            ("JK", "Jammu and Kashmir"),
                            ("MN", "Manipur"),
                            ("AS", "Assam"),
                            ("RJ", "Rajasthan"),
                            ("UP", "Uttar Pradesh"),
                            ("CG", "Chhattisgarh"),
                            ("LD", "Lakshadweep"),
                            ("OD", "Odisha"),
                            ("KL", "Kerala"),
                            ("AN", "Andaman and Nicobar Islands"),
                            ("PB", "Punjab"),
                            ("WB", "West Bengal"),
                            ("SK", "Sikkim"),
                            ("MH", "Maharashtra"),
                            ("MZ", "Mizoram"),
                            ("AP", "Andhra Pradesh"),
                            ("NL", "Nagaland"),
                            ("GA", "Goa"),
                            ("JH", "Jharkhand"),
                            ("BR", "Bihar"),
                            ("DN", "Dadra and Nagar Haveli"),
                            ("UK", "Uttarakhand"),
                            ("HP", "Himachal Pradesh"),
                            ("GJ", "Gujarat"),
                            ("DD", "Daman and Diu"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
