# Generated by Django 4.2.4 on 2023-08-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_customer_state_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="state",
            field=models.CharField(
                choices=[
                    ("DD", "Daman and Diu"),
                    ("KA", "Karnataka"),
                    ("AP", "Andhra Pradesh"),
                    ("LD", "Lakshadweep"),
                    ("LA", "Ladakh"),
                    ("WB", "West Bengal"),
                    ("OD", "Odisha"),
                    ("JK", "Jammu and Kashmir"),
                    ("RJ", "Rajasthan"),
                    ("KL", "Kerala"),
                    ("BR", "Bihar"),
                    ("TN", "Tamil Nadu"),
                    ("MN", "Manipur"),
                    ("DN", "Dadra and Nagar Haveli"),
                    ("AS", "Assam"),
                    ("UP", "Uttar Pradesh"),
                    ("NL", "Nagaland"),
                    ("TR", "Tripura"),
                    ("HR", "Haryana"),
                    ("PY", "Pondicherry"),
                    ("GJ", "Gujarat"),
                    ("TS", "Telangana"),
                    ("HP", "Himachal Pradesh"),
                    ("UK", "Uttarakhand"),
                    ("PB", "Punjab"),
                    ("CH", "Chandigarh"),
                    ("GA", "Goa"),
                    ("JH", "Jharkhand"),
                    ("MZ", "Mizoram"),
                    ("ML", "Meghalaya"),
                    ("AR", "Arunachal Pradesh"),
                    ("SK", "Sikkim"),
                    ("AN", "Andaman and Nicobar Islands"),
                    ("MP", "Madhya Pradesh"),
                    ("MH", "Maharashtra"),
                    ("DL", "Delhi"),
                    ("CG", "Chhattisgarh"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("BS", "Biscuits Snack"),
                    ("VG", "Vegetables"),
                    ("FM", "Fresh Meat"),
                    ("FB", "Fresh Bakery"),
                    ("FR", "Fresh Fruits"),
                    ("SF", "Sea Foods"),
                    ("FM2", "Fresh Milk"),
                    ("FD", "Fruit Drinks"),
                ],
                max_length=25,
            ),
        ),
    ]
