# Generated by Django 4.2.4 on 2023-08-19 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0007_alter_customer_state_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="state",
            field=models.CharField(
                choices=[
                    ("LD", "Lakshadweep"),
                    ("KA", "Karnataka"),
                    ("WB", "West Bengal"),
                    ("HP", "Himachal Pradesh"),
                    ("UK", "Uttarakhand"),
                    ("AR", "Arunachal Pradesh"),
                    ("JH", "Jharkhand"),
                    ("CH", "Chandigarh"),
                    ("OD", "Odisha"),
                    ("SK", "Sikkim"),
                    ("DL", "Delhi"),
                    ("LA", "Ladakh"),
                    ("ML", "Meghalaya"),
                    ("JK", "Jammu and Kashmir"),
                    ("PB", "Punjab"),
                    ("AS", "Assam"),
                    ("MZ", "Mizoram"),
                    ("DN", "Dadra and Nagar Haveli"),
                    ("UP", "Uttar Pradesh"),
                    ("HR", "Haryana"),
                    ("MH", "Maharashtra"),
                    ("KL", "Kerala"),
                    ("TN", "Tamil Nadu"),
                    ("TS", "Telangana"),
                    ("AN", "Andaman and Nicobar Islands"),
                    ("BR", "Bihar"),
                    ("AP", "Andhra Pradesh"),
                    ("NL", "Nagaland"),
                    ("MP", "Madhya Pradesh"),
                    ("GJ", "Gujarat"),
                    ("PY", "Pondicherry"),
                    ("CG", "Chhattisgarh"),
                    ("DD", "Daman and Diu"),
                    ("TR", "Tripura"),
                    ("MN", "Manipur"),
                    ("RJ", "Rajasthan"),
                    ("GA", "Goa"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("FM2", "Fresh Milk"),
                    ("FB", "Fresh Bakery"),
                    ("SF", "Sea Foods"),
                    ("FR", "Fresh Fruits"),
                    ("VG", "Vegetables"),
                    ("BS", "Biscuits Snack"),
                    ("FD", "Fruit Drinks"),
                    ("FM", "Fresh Meat"),
                ],
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "razorpay_payment_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("paid", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderPlaced",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("ordered_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Accepted", "Accepted"),
                            ("Pending", "Pending"),
                            ("Cancel", "Cancel"),
                            ("On The Way", "On The Way"),
                            ("Delivered", "Delivered"),
                            ("Packed", "Packed"),
                        ],
                        default="Pending",
                        max_length=100,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.customer"
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.payments",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
