# Generated by Django 4.2.4 on 2023-08-20 08:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0009_alter_customer_state_alter_orderplaced_status_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="WhishlistAdminModel", new_name="Whishlist",),
        migrations.AlterField(
            model_name="customer",
            name="state",
            field=models.CharField(
                choices=[
                    ("MH", "Maharashtra"),
                    ("LA", "Ladakh"),
                    ("TN", "Tamil Nadu"),
                    ("GA", "Goa"),
                    ("GJ", "Gujarat"),
                    ("TR", "Tripura"),
                    ("RJ", "Rajasthan"),
                    ("DN", "Dadra and Nagar Haveli"),
                    ("KA", "Karnataka"),
                    ("CH", "Chandigarh"),
                    ("MN", "Manipur"),
                    ("PY", "Pondicherry"),
                    ("JK", "Jammu and Kashmir"),
                    ("KL", "Kerala"),
                    ("MZ", "Mizoram"),
                    ("AR", "Arunachal Pradesh"),
                    ("PB", "Punjab"),
                    ("CG", "Chhattisgarh"),
                    ("HP", "Himachal Pradesh"),
                    ("DD", "Daman and Diu"),
                    ("AN", "Andaman and Nicobar Islands"),
                    ("UP", "Uttar Pradesh"),
                    ("HR", "Haryana"),
                    ("OD", "Odisha"),
                    ("MP", "Madhya Pradesh"),
                    ("WB", "West Bengal"),
                    ("DL", "Delhi"),
                    ("NL", "Nagaland"),
                    ("AP", "Andhra Pradesh"),
                    ("AS", "Assam"),
                    ("LD", "Lakshadweep"),
                    ("UK", "Uttarakhand"),
                    ("SK", "Sikkim"),
                    ("ML", "Meghalaya"),
                    ("TS", "Telangana"),
                    ("JH", "Jharkhand"),
                    ("BR", "Bihar"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="orderplaced",
            name="status",
            field=models.CharField(
                choices=[
                    ("Cancel", "Cancel"),
                    ("On The Way", "On The Way"),
                    ("Delivered", "Delivered"),
                    ("Pending", "Pending"),
                    ("Packed", "Packed"),
                    ("Accepted", "Accepted"),
                ],
                default="Pending",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("SF", "Sea Foods"),
                    ("FM2", "Fresh Milk"),
                    ("BS", "Biscuits Snack"),
                    ("FR", "Fresh Fruits"),
                    ("FD", "Fruit Drinks"),
                    ("FM", "Fresh Meat"),
                    ("FB", "Fresh Bakery"),
                    ("VG", "Vegetables"),
                ],
                max_length=25,
            ),
        ),
    ]
